name: Build and Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-scan:
    name: Unit Tests + SonarQube + Docker + OWASP ZAP API Scan
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step 3: Install dependencies and run Unit Tests with Coverage
      - name: Run Unit Tests with Coverage
        run: |
          pip install pytest flask pytest-cov
          python -m pytest src/test_secure_example.py --cov=main --cov-report=xml -v

      # Step 4: SonarQube Scan
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.python.coverage.reportPaths=coverage.xml

      # Step 5: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t myapp:latest .

      # Step 6: Run Docker Container
      - name: Run Docker Container
        run: |
          docker run -d -p 8000:5000 --name myapp_container myapp:latest

      # Step 7: Wait for Flask app to be ready
      - name: Wait for Flask app to be ready
        run: |
          sleep 10  # Wait for 10 seconds to ensure Flask app has started

      # Step 8: ZAP API Scan
      - name: ZAP API Scan
        uses: zaproxy/action-api-scan@v0.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}         # default GitHub token
          target: http://host.docker.internal:8000/api  # Replace with your API base URL
          format: openapi                             # 'openapi', 'soap', or 'graphql'
          docker_name: ghcr.io/zaproxy/zaproxy:latest
          cmd_options: "-d"                            # Debug mode
          issue_title: ZAP API Scan Report
          fail_action: true
          allow_issue_writing: true
          artifact_name: zap_api_report

      # Step 9: Upload ZAP API Report as Artifact
      - name: Upload ZAP API Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-api-report
          path: /zap_api_report
          if-no-files-found: warn
          compression-level: 6
          overwrite: false

      # Step 10: Stop Docker container
      - name: Stop Docker Container
        run: |
          docker stop myapp_container
          docker rm myapp_container
