name: Build and Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-scan:
    name: Unit Tests + SonarQube + Docker + OWASP ZAP
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step 3: Install dependencies and run Unit Tests with Coverage
      - name: Run Unit Tests with Coverage
        run: |
          pip install pytest flask pytest-cov
          python -m pytest src/test_secure_example.py --cov=main --cov-report=xml -v

      # Step 4: SonarQube Scan
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.python.coverage.reportPaths=coverage.xml

      # Step 5: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t myapp:latest .

      # Step 6: Run Docker Container
      - name: Run Docker Container
        run: |
          docker run -d -p 8000:5000 myapp:latest  # Expose Flask app on port 8000

     

      # Step 8: Run OWASP ZAP Full Scan
      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.13.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use default GitHub token
          target: http://localhost:8000  # Flask app running on port 8000
          docker_name: ghcr.io/zaproxy/zaproxy:latest
          cmd_options: -quickstart -config api.addrs.addr.name=.*  
          issue_title: ZAP Full Scan Report
          fail_action: true
          allow_issue_writing: true
          artifact_name: zap_scan_report

      # Step 9: Upload ZAP HTML Report as Artifact
      - name: Upload ZAP HTML Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: /zap/zap_report.html
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
